export const Boards = [
  "Andhra Pradesh Board of Intermediate Education(BIEAP)",
  "Andhra Pradesh Board of Secondary Education (BSEAP)",
  "Andhra Pradesh Open School Society (APOSS)",
  "Assam Higher Secondary Education Council(AHSEC)",
  "Assam Sanskrit Board (ASB)",
  "Assam State Open School (ASOS)",
  "Bihar Board of Open Schoooptionng and Examination (BBOSE)",
  "Bihar Sanskrit Shiksha Board (BSSB)",
  "Bihar School Examination Board (BSEB )",
  "Bihar State Madrasa Education Board (BSMEB)",
  "Board of High School and Intermediate Education Uttar Pradesh (BHSIEUP)",
  "Board Of Higher Secondary Education, Delhi(BHSE)",
  "Board of Secondary Education, Madhya Pradesh(MPBSE)",
  "Board of Secondary Education, Rajasthan(RBSE)",
  "CBSE",
  "Chhattisgarh Board of Secondary Education(CGBSE)",
  "Goa Board of Secondary and Higher SecondaryEducation (GBSHSE)",
  "Grameen Mukt Vidyalayi Shiksha Sansthan(GMVSS)",
  "Gujarat Secondary Education Board (GSEB)",
  "Haryana Board of School Education (BSEH)",
  "Himachal Pradesh Board of School Education(HPBOSE)",
  "Himachal Pradesh State Open School (HPSOS)",
  "ICSE",
  "Jammu and Kashmir State Board of School Education (JKBOSE)",
  "Jammu and Kashmir State Open School (JKSOS)",
  "Jharkhand Academic Council (JAC)",
  "Karnataka Secondary Education Examination Board (KSEEB)",
  "Kerala Higher Secondary Examination Board(DHSE)",
  "Kerala State Open School (SCOLE)",
  "Madhya Pradesh State Open School (MPSOS)",
  "Madhyamik Shiksha Parishad, Delhi (MSP)",
  "Maharashtra State Board of Secondary and Higher Secondary Education (MSBSHSE)",
  "Meghalaya Board of School Education (MBOSE)",
  "Mizoram Board of School Education (MBSE)",
  "Nagaland Board of School Education (NBSE )",
  "National Institute of Open Schoooptionng(NIOS)",
  "Odisha Board of Secondary Education (BSE)",
  "Odisha Council of Higher Secondary Education(CHSE)",
  "Punjab School Education Board (PSEB)",
  "Rajasthan State Open School (RSOS)",
  "Tamil Nadu Board of Secondary Education(DGE)",
  "Telangana Board of Intermediate Education(TSBIE)",
  "Telangana Board of Secondary Education (SSC)",
  "Tripura Board of Secondary Education (TBSE)",
  "Uchchatar Madhyamic Shiksha Parishad,Under MSMED act 2006,Koshambi (UMSM)",
  "Uttarakhand Board of School Education (UBSE)",
  "West Bengal Board of Madrasah Education(WBBME)",
  "West Bengal Board of Primary Education(WBBPE)",
  "West Bengal Board of Secondary Education(WBBSE)",
  "West Bengal Council of Higher SecondaryEducation (WBCHSE)",
  "West Bengal Council of Rabindra OpenSchoooptionng (WBCROS)",
];
